src/Entity/Pin.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\PinRepository;
use App\Entity\Traits\Timestampable;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
/**
 * @ORM\Entity(repositoryClass=PinRepository::class)
 * @ORM\Table(name="pins")
 * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks
 */
class Pin
{

    use Timestampable;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     *@Assert\Length(min=3)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     * @Assert\Length(max=15)
     */
    private $description;
    
    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="pin_image", fileNameProperty="imageName")
     * @Assert\Image(maxSize="8M")
     * @var File|null
     */
    private $imageFile;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageName;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="pins")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }
    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->setUpdatedAt (new \DateTimeImmutable);
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use App\Entity\Traits\Timestampable;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="users")
 * @ORM\HasLifecycleCallbacks
 */
class User implements UserInterface
{
    use Timestampable;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\OneToMany(targetEntity=Pin::class, mappedBy="user", orphanRemoval=true)
     */
    private $pins;

    public function __construct()
    {
        $this->pins = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @return Collection|Pin[]
     */
    public function getPins(): Collection
    {
        return $this->pins;
    }

    public function addPin(Pin $pin): self
    {
        if (!$this->pins->contains($pin)) {
            $this->pins[] = $pin;
            $pin->setUser($this);
        }

        return $this;
    }

    public function removePin(Pin $pin): self
    {
        if ($this->pins->removeElement($pin)) {
            // set the owning side to null (unless already changed)
            if ($pin->getUser() === $this) {
                $pin->setUser(null);
            }
        }

        return $this;
    }
    public function getFullName():string {
        return $this->getFirstName() .' '.$this->getLastName();
    }
}

src/Form/PinType.php
<?php

namespace App\Form;

use App\Entity\Pin;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PinType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
                ->add('imageFile', VichImageType::class, [
                    'label' =>'Image(JPEG OU PNG file)',
                    'required' => false,
                    'allow_delete' => true,
                    'download_uri' => false,
                    'imagine_pattern'=>'squared_thumbnail_small'
                
                
                ])
            ->add('title')
            ->add('description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pin::class,
        ]);
    }
}

src/Controller/PinsController.php
<?php

namespace App\Controller;

use App\Entity\Pin;
use App\Form\PinType;
use App\Repository\PinRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PinsController extends AbstractController
{
    /**
     * @Route("/", name="app_home",methods="GET")
     */
    public function index(PinRepository $pinRepository): Response
    {
        $pins=$pinRepository->findBy([],['createdAt'=>'DESC']);
        return $this->render('pins/index.html.twig',compact('pins'));
    }
    /** 
      * @Route("/pins/create", name="app_pins_create",methods={"GET","POST"})
     */
    public function create(Request $request,EntityManagerInterface $em,UserRepository $userRepo){
        $pin=new Pin;
        $form = $this->createForm(PinType::class,$pin);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $alpha=$userRepo->findOneBy(['email'=>'alpha@example.com']);
            $pin->setUser($alpha);
            $em->persist($pin);
            $em->flush();
            $this->addFlash('success','Pin successfully created');
            return $this->redirectToRoute('app_home');

        }
        return $this->render('pins/create.html.twig',[
            'form'=>$form->createView(),
        ]);
    }
    /**
     * @Route("/pins/{id<\d+>}", name="app_pins_show",methods="GET")
     */
    public function show(Pin $pin){
        return $this->render('pins/show.html.twig',compact('pin'));
    }
    /**
     * @Route("/pins/{id<\d+>}/edit", name="app_pins_edit",methods={"GET", "PUT"})
     */
    public function edit(Request $request,EntityManagerInterface $em,Pin $pin)
    {
        $form = $this->createForm(PinType::class,$pin,[
            'method' =>'PUT',
        ]);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em->flush();
            $this->addFlash('success','Pin successfully updated!');
            return $this->redirectToRoute('app_home');
        }
        return $this->render('pins/edit.html.twig',[
            'pin'=>$pin,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/pins/{id<\d+>}/delete", name="app_pins_delete",methods={"DELETE"})
     */
    public function delete(Request $request,EntityManagerInterface $em,Pin $pin):Response
    {
        if($this->isCsrfTokenValid('pin_deletion_'.$pin->getId(),$request->request->get('csrf_token')))
        {
        $em->remove($pin);
        $em->flush();
        $this->addFlash('info','Pin successfully deleted!');
        }
        return $this->redirectToRoute('app_home');
    }
}

templates/pins/_form.html.twig
{{ form_start(form) }}
    {{form_widget(form)}}

<input type="submit" value="{{ submitButtonText ?? 'Create Pin'}}" class="btn 
btn-primary btn-block" formnovalidate>
{{ form_end(form) }}

templates/pins/create.html.twig
{% extends "layouts/base.html.twig" %}
{% block title 'New pin' %}

{% block body %}
	<div class="row">
		<div class="col-md-6 mx-auto">
			<h1>Create Pin</h1>
			{{ include('pins/_form.html.twig') }}

		</div>
	</div>
{% endblock %}

templates/pins/edit.html.twig
{% extends "layouts/base.html.twig" %}
{% block title 'Edit pin #'~ pin.id %}


{% block body %}
	<div class="row">
		<div class="col-md-6 mx-auto">
			<h1>Edit Pin #{{ pin.id }}</h1>
			{{ include('pins/_form.html.twig',{submitButtonText:'Update Pin'}) }}

		</div>
	</div>


{% endblock %}

templates/pins/index.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title %}Panterest
{% endblock %}

{% block body %}
	{% if pins|length > 0 %}
		<h1 class=" mb-4 text-center text-muted">{{ pluralize (pins|length , 'Pin')}}pins</h1>
		{% for row in pins|batch(3) %}
			<div class="row mb-5">
				{% for pin in pins %}
					<div class="col-md-4">
						<article class=" pin bg-white rounded shadow">
							<div class="mw-100  rounded-top overflow-hidden">
								<a href="{{path ('app_pins_show',{id:pin.id})}}">
									<img src="{{ vich_uploader_asset (pin) }}" alt="{{ pin.title }}" class="w-100 "/>
								</a>
							</div>
							<h2 class="h5 pl-3 pt-3">
                            <a href="{{path ('app_pins_show',{id:pin.id})}}" class="text-secondary text-decoration-none">{{pin.title}}</a>
							</h2>
							<p class="pl-3 pb-3 text-muted">
								<small>Submitted  by {{pin.user.fullName}}</small></p>
						</article>
					</div>
				{% endfor %}
			</div>
		{% endfor %}
	{% else %}
		<p class=" mt-5 h1 text-center">Pas de Pins.<a href="{{path ('app_pins_create')}}">Be the first!</a>
		</p>
	{% endif %}

{% endblock %}

templates/pins/show.html.twig
{% extends "layouts/base.html.twig" %}
{% block title pin.title %}
{% block body %}
	<div class="row">
		<div class="col-md-6 mx-auto">
			<article class=" pin bg-white rounded shadow">
				<div class="mw-100 rounded-top overflow-hidden">
						<img src="{{ vich_uploader_asset (pin) }}" alt="{{ pin.title }}" class="w-100 "/>
				</div>
				<div class="p-3">
				<h1 class="h5 text-secondary">
				{{pin.title}}
				</h1>
				<p class="text-muted">
					<small>Submitted
						<time datetime="{{pin.createdAt|date('Y-m-d H:i:s')}}">{{pin.createdAt|ago }}
							by {{pin.user.fullName}}</time>
					</small>
				</p>
				<p class="pt-3 text-break">{{pin.description}}</p>
				<div class="pt-3">
					<a href="{{path ('app_pins_edit',{id:pin.id})}} " class="btn btn-light">Edit</a>
					<a href="#" onclick="event.preventDefault(); confirm('Are you sure') &&
																																		document.getElementById('js-pin-delete-form').submit();" class="btn btn-light">Delete</a>
					<form id="js-pin-delete-form" action="{{path ('app_pins_delete',{id:pin.id})}}" method="post" style="display:none;">
						<input type="hidden" name="csrf_token" value="{{ csrf_token ('pin_deletion_'~ pin.id)}}">
						<input type="hidden" name="_method" value="DELETE">
					</form>
				</div>
				</div>
			</article>
		</div>
	</div>
{% endblock %}